### ISSUE TITLE
Стрелки у компаний куда-то пропали +котировки +дневной доход

### ISSUE THREAD

**Issue by montisgroup** [montisgroup/beatmarket#183]
![image](https://user-images.githubusercontent.com/78232283/120756694-4015f580-c518-11eb-8ed6-1c7c9ac5c1e8.png)

1) У верхней есть стрелка, у нижней, как видишь, нет.

2) Справа у компании 1 - это число бумаг. Тут оно не нужно. Вместо 1 выводим дневной доход в %

3) Хорошо бы текущую цену тут же куда-то воткнуть. Посмотри, может там есть место. Прям, можно даже под тикером, мелко-мелко

**Comment by AlimKhalilev** [comment]
![image](https://user-images.githubusercontent.com/22529797/120832134-facde400-c568-11eb-8675-d43f092b6864.png)
![image](https://user-images.githubusercontent.com/22529797/120832161-03beb580-c569-11eb-8136-ebf9218ee19f.png)
![image](https://user-images.githubusercontent.com/22529797/120833063-066dda80-c56a-11eb-8ec0-fd12a87a5f6e.png)
